services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "unicesumar"
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    ports:
      - 8080:8080
